openapi: 3.0.0

info:

  title: STD23054 - TD1
  version: 1.0.0

servers:

  - url: https://localhost.std23054.com

paths:

  /customers:
    get:

      parameters:
        - in: query
          name: Page
          schema:
            type: integer
          required : true
          description : Parametre obligatoire

        - in: query
          name : PageSize
          schema :
            type : integer
          required : true
          description : Parametre obligatoire  

      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"
  
    post:
      requestBody: 
        description: Attend la liste des clients
        required: true
        content:
          application/json:
            schema:
              $ref : "#/components/schemas/Customer"
      responses : 
        '200':
          description : Succès
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

components:

  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        id:
          type: string
