openapi: 3.0.3
info:
  title: STD23054 - TD2
  version: '1.0.2'
servers:
  - url: https://localhost.std23054.com
paths:
  /customers:
    get:
      summary: Récupérer une liste de clients
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
          description: Le numéro de la page à récupérer.
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
          description: Le nombre d'éléments par page.
      responses:
        200:
          description: Une liste de clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Créer une liste de clients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: Le nom du client.
                  age:
                    type: integer
                    description: L'âge du client.
      responses:
        200:
          description: Une liste de clients créés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    put:
      summary: Mettre à jour une liste de clients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Customer'
      responses:
        200:
          description: Une liste de clients mis à jour
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    delete:
      summary: Supprimer des clients par ID
      parameters:
        - in: query
          name: ids
          schema:
            type: array
            items:
              type: string
          required: true
          description: Une liste des IDs des clients à supprimer.
      responses:
        200:
          description: Une liste de clients supprimés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
          description: L'identifiant unique du client.
        name:
          type: string
          description: Le nom du client.
        age:
          type: integer
          description: L'âge du client.
    CustomerIdentifier:
      type: object
      properties:
        id:
          type: string
          description: L'identifiant unique du client.
